version: 2
jobs:
  build:
    machine:
      docker_layer_caching: true  # faster builds
    working_directory: ~/go/src/github.com/marccarre/todo.txt-googletasks
    steps:
      - checkout
      - run: |
          make build
      - run: |
          echo -e "$TOKEN_BASE64_ENCODED" | base64 --decode > ~/.cache/todo.txt-googletasks_3411736364
          make \
            CI=$CI \
            COVERALLS_TOKEN=$COVERALLS_TOKEN \
            CLIENT_ID=$CLIENT_ID \
            CLIENT_SECRET=$CLIENT_SECRET \
            test
      - run: |
          docker login quay.io -u $DOCKER_USER -p $DOCKER_PASS
          make docker-build
          make docker-push
